import json
from openai import OpenAI
from dataclasses import dataclass
from src.config import Config
from src.utils import logger

@dataclass
class DesignPlan:
    raw_prompt: str
    visual_prompt: str
    title_text: str
    mood: str

class SemanticPlanner:
    def __init__(self):
        self.client = OpenAI(api_key=Config.OPENAI_API_KEY)

    def create_plan(self, user_prompt: str) -> DesignPlan:
        """
        Uses GPT-4o to decompose the user prompt into structured JSON.
        Separates semantic intent (image) from textual intent (overlay).
        """
        logger.info(f"Sending prompt to GPT-4o for decomposition: '{user_prompt}'")

        system_instruction = (
            "You are an expert YouTube Thumbnail designer. "
            "Your goal is to separate the USER PROMPT into two parts: "
            "1. 'visual_prompt': A DALL-E 3 prompt describing the background scene. "
            "   IMPORTANT: The visual prompt must explicitly say 'no text, no words, clean background'. "
            "   It should describe the subject matter physically (e.g., 'a shocked man looking at a laptop'). "
            "2. 'title_text': The exact punchy text to overlay on the image (max 6 words). "
            "3. 'mood': The aesthetic vibe (e.g., 'dark_suspense', 'bright_educational'). "
            "Return JSON only."
        )

        try:
            response = self.client.chat.completions.create(
                model="gpt-4o",
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": f"Create a design plan for: {user_prompt}"}
                ],
                temperature=0.7
            )

            data = json.loads(response.choices[0].message.content)
            
            # Defensive check: Ensure visual prompt includes negative constraints
            clean_visual = data['visual_prompt']
            if "no text" not in clean_visual.lower():
                clean_visual += ", no text, empty copy space, clean composition"

            logger.info("Plan successfully generated by LLM.")
            
            return DesignPlan(
                raw_prompt=user_prompt,
                visual_prompt=clean_visual,
                title_text=data['title_text'].upper(),
                mood=data.get('mood', 'neutral')
            )

        except Exception as e:
            logger.error(f"LLM Planning failed: {e}")
            # Fallback logic for resilience
            return DesignPlan(
                raw_prompt=user_prompt,
                visual_prompt=f"{user_prompt}, high quality abstract background, no text",
                title_text=user_prompt[:20].upper(),
                mood="fallback"
            )